# Generated by Django 3.2.9 on 2021-12-01 14:19

from django.db import migrations, models
import upload_app.models
import upload_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_alter_item_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='item',
            name='from_storage',
            field=models.FilePathField(default=1, path=upload_app.models.images_path, verbose_name='From Storage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.FileField(upload_to='uploads', validators=[upload_app.validators.validate_file_extension]),
        ),
    ]
